---
title: "Homework Assignment 1"
author: "Student:  "
format: html
toc: false

---


# Instructions

Please type your answer within the document and render a html file to submit to Canvas

---

## 1 — Identify each variable as quantitative or qualitative

A. The height of a newborn in a hospital is `quantitative`

B. The age of a football player is `quantitative`

C. The student social security number is `qualitative`

D. The blood type of a middle school teacher is `qualitative`

---

## 2 — Classify each quantitative variable as discrete or continuous

A. Number of siblings of a student is `discrete`

B. Number of dead batteries in a box of dozen batteries is `discrete`

C. Time it takes to respond to a question is `continuous`

D. Systolic blood pressure is `continuous`

---

## 3 — Observational study or designed experiment?

A. A study of stress and its relationship to obesity where participants were surveyed: `Observational study`
B. Longitudinal study of healthy people to see who develops lung cancer (smoking status recorded): `designed experiment`
C. Clinical trial randomly dividing participants into two diet groups to measure blood pressure: `designed experiment`
D. Rats randomly divided into exposed/unexposed groups to radiation and observed for cancer: `designed experiment`

---


## 4 — Population / variable / statistic questions

A Lake Tahoe Community College instructor is interested in the mean number of days math students are absent during a quarter.

a. What is the population she is interested in?  `D`

* (A) All Lake Tahoe Community College students
* (B) All Lake Tahoe Community College English students
* (C) All Lake Tahoe Community College students in her classes
* (D) All Lake Tahoe Community College math students

b. Consider X represent the number of days a LTCC math student is absent. In this case X is an example of a: `Data`

* (A) Variable
* (B) Population
* (C) Statistic
* (D) Data

c. The instructor’s sample produces a mean number of days absent of `3.5` days. This value is an example of a: `Statistic`

* (A) Parameter
* (B) Data
* (C) Statistic
* (D) Variable


---

## 5 — Representative or non-representative?

For each study below mark A (REPRESENTATIVE) or B (NON-REPRESENTATIVE):

1. Sample of 300 dentists from Seattle used to estimate median income of all Seattle residents. `A`
2. Sample of 200 professional football players to estimate mean weight of all adult males.  `A`
3. Simple random sample of 10 men over age 18 to estimate mean height of all adult males.  `A`
4. Simple random sample of 1000 voters to determine candidate chances.  `B`
5. Sample of 400 patients from a local hospital to estimate mean cholesterol of U.S. citizens.  `A`

---



## 6 — Population & sample means (12 students)

Population test scores: `78, 84, 87, 70, 92, 78, 59, 82, 81, 64, 97, 76`

``` {python}
#| echo: false
from statistics import mean
population_mean = mean([78, 84, 87, 70, 92, 78, 59, 82, 81, 64, 97, 76])
random_sample_1 = mean([92, 82, 87])
sample_2 = mean([59, 84, 64])
```

A. What is the population mean grade? (round to 1 decimal)
Answer: `{python} population_mean`

B. A random sample of size 3: sample `92, 82, 87` — sample mean = `{python} random_sample_1`; compare to population mean: `{python} f'{(((random_sample_1 / population_mean) - 1) * 100):.1f}'`% larger than the population mean.

C. Another sample of size 3: sample `59, 84, 64` — sample mean = `{python} sample_2`; compare to population mean: `{python} f'{abs(((sample_2 / population_mean) - 1) * 100):.1f}'`% lower than the population mean.

D. What can you conclude about relationship between a sample mean and the population mean? (`A`)

* (A) The sample mean varies from sample to sample.
* (B) No matter how many times we select a sample, the sample mean is always equal to the population mean.
* (C) Every time we select a sample, the sample mean always overestimates the population mean.
* (D) Every time we select a sample, the sample mean always underestimates the population mean.



---

## 7 — Sample standard deviation

Given sample: `3, 17, 25, 15, 11, 17, 28, 15, 4`

A. What symbol denotes the sample standard deviation? $\sigma$

``` {python}
#| echo: false
from statistics import stdev
```

B. Find the sample standard deviation (round to 2 decimals): `{python} f'{stdev([3, 17, 25, 15, 11, 17, 28, 15, 4]):.2f}'`

---

## 8 — Sleep survey (15 students)

Sample data: `6.5, 6.5, 7, 7, 5.5, 7.5, 6, 8.5, 8, 5.5, 5.5, 5, 6.5, 8, 5`

``` {python}
#| echo: false
from statistics import quantiles
sleep_data = [6.5, 6.5, 7, 7, 5.5, 7.5, 6, 8.5, 8, 5.5, 5.5, 5, 6.5, 8, 5]
# could use a function from numpy, but that isn't needed
sleep_data_range = max(sleep_data) - min(sleep_data)
sleep_data_stdev = stdev(sleep_data)
# splits the data into 4 ranges to do an iqr with q3 and q1
q1, q2, q3 = quantiles(sleep_data, n=4)
sleep_data_iqr = q3 - q1
```

A. Range = `{python} sleep_data_range`

B. Standard deviation = `{python} f'{sleep_data_stdev:.2f}'` (round to 2 decimals)

C. IQR = `{python} sleep_data_iqr`

D. Suppose the 5th data value was recorded as `55` instead of `5.5`. Recompute new range and SD:

``` {python}
#| echo: false
updated_sleep_data = [6.5, 6.5, 7, 7, 55, 7.5, 6, 8.5, 8, 5.5, 5.5, 5, 6.5, 8, 5]
# could use a function from numpy, but that isn't needed
updated_sleep_data_range = max(updated_sleep_data) - min(updated_sleep_data)
updated_sleep_data_stdev = stdev(updated_sleep_data)
# splits the data into 4 ranges to do an iqr with q3 and q1
updated_q1, updated_q2, updated_q3 = quantiles(updated_sleep_data, n=4)
updated_sleep_data_iqr = updated_q3 - updated_q1
```

* New range = `{python} updated_sleep_data_range`
* New SD = `{python} f'{updated_sleep_data_stdev:.2f}'` (round to 2 decimals)
* New IQR = `{python} updated_sleep_data_iqr`




## 9 — Compute mean & median; skewness

Grades: `98, 92, 91, 91, 87, 85, 85, 82, 77, 76, 61`

``` {python}
#| echo: false
from statistics import median
grades = [98, 92, 91, 91, 87, 85, 85, 82, 77, 76, 61]
grades_mean = mean(grades)
grades_median = median(grades)
```

Mean = `{python} grades_mean`

Median = `{python} grades_median`

- Present the Histogram

``` {python}
#| echo: false
from matplotlib import pyplot as plt

plt.hist(grades, bins=4, color='purple', edgecolor='black')

plt.xlabel('Grades')
plt.ylabel('Frequency')
plt.title('Grades Histogram')

plt.show()
```

- Is this dataset `SKEWED RIGHT`, `SYMMETRIC`, or `SKEWED LEFT`?

`SKEWED RIGHT`
